# Generated by Django 4.2.5 on 2024-07-27 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'وضعیت',
                'verbose_name_plural': 'وضعیت ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True, auto_now_add=True, verbose_name='زمان ایجاد شدن')),
                ('name', models.CharField(max_length=63, verbose_name='نام تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=63, null=True, verbose_name='زیر عنوان')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('status', models.ForeignKey(default='انجام نشده', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status', to='todolist.status', verbose_name='وضعیت')),
                ('tags', models.ManyToManyField(related_name='tags', to='todolist.tag', verbose_name='تگ ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظیفه ها',
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='نام')),
                ('todos', models.ManyToManyField(to='todolist.todo', verbose_name='وظیفه ها')),
            ],
            options={
                'verbose_name': 'لیست وظیفه',
                'verbose_name_plural': 'لیست وظیفه ها',
            },
        ),
    ]
