# Generated by Django 5.0.6 on 2024-08-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='todos',
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_list',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo_list', to='todolist.todolist', verbose_name='لیست وظایف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='todolist.status', verbose_name='وضعیت'),
        ),
    ]
