# Generated by Django 5.0.6 on 2024-08-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_todolist_todos_todo_todo_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='todolist.tag', verbose_name='تگ ها'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_list', to='todolist.todolist', verbose_name='لیست وظیفه ها'),
        ),
    ]
