# Generated by Django 5.0.6 on 2024-06-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_status_name_alter_tag_name_alter_todo_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'لیست وظیفه', 'verbose_name_plural': 'لیست وظیفه ها'},
        ),
    ]
