# Generated by Django 5.0.6 on 2024-08-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todo_status'),
        ('todolist', '0003_alter_todo_tags_alter_todo_todo_list'),
    ]

    operations = [
    ]
