# Generated by Django 5.0.6 on 2024-08-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_merge_20240803_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='todos', to='todolist.tag', verbose_name='تگ ها'),
        ),
    ]
