# Generated by Django 5.0.6 on 2024-07-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_remove_todo_name_todo_subtitle_todo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='subtitle',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='زیر عنوان'),
        ),
    ]
